# Generated by Django 5.1.4 on 2024-12-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dailyQuests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest_name', models.CharField(max_length=50)),
                ('quest_description', models.CharField(max_length=200)),
                ('experience_points', models.IntegerField()),
                ('common_items', models.JSONField()),
                ('uncommon_items', models.JSONField()),
                ('rare_items', models.JSONField()),
            ],
        ),
    ]
