# Generated by Django 5.1.4 on 2024-12-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customuser_number_of_quests'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='base_number_of_quests',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='number_of_quests',
            field=models.IntegerField(default=4),
        ),
    ]
