# Generated by Django 5.1.4 on 2024-12-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_customuser_base_number_of_quests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='completed_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='target_num_quests',
            field=models.IntegerField(default=2),
        ),
    ]
