# Generated by Django 5.1.4 on 2024-12-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_customuser_completed_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=50)),
                ('backpack', models.JSONField()),
                ('skills', models.JSONField()),
                ('current_equip_items', models.JSONField()),
            ],
        ),
    ]
