# Generated by Django 5.1.4 on 2024-12-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_customuser_character'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=50)),
                ('damage', models.IntegerField(blank=True, null=True)),
                ('healing', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('level_required', models.IntegerField()),
                ('damage', models.IntegerField(blank=True, null=True)),
                ('healing', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='character',
            name='backpack',
        ),
        migrations.RemoveField(
            model_name='character',
            name='current_equip_items',
        ),
        migrations.RemoveField(
            model_name='character',
            name='skills',
        ),
        migrations.AddField(
            model_name='character',
            name='backpack',
            field=models.ManyToManyField(blank=True, to='core.item'),
        ),
        migrations.AddField(
            model_name='character',
            name='current_equip_items',
            field=models.ManyToManyField(blank=True, related_name='equipped_items', to='core.item'),
        ),
        migrations.AddField(
            model_name='character',
            name='skills',
            field=models.ManyToManyField(blank=True, to='core.skill'),
        ),
    ]
