# Generated by Django 5.1.4 on 2024-12-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_item_skill_remove_character_backpack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='drop_rate',
            field=models.IntegerField(default=0),
        ),
    ]
