# Generated by Django 5.1.4 on 2024-12-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_item_drop_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='uses',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
