# Generated by Django 5.1.4 on 2024-12-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_item_uses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='uses',
        ),
        migrations.AddField(
            model_name='item',
            name='drop_class',
            field=models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=20),
        ),
    ]
