# Generated by Django 5.1.4 on 2024-12-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_item_uses_item_drop_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('ingredient', 'Ingredient'), ('weapon', 'Weapon'), ('armor', 'Armor'), ('object', 'Object')], default='ingredient', max_length=20),
        ),
    ]
