# Generated by Django 5.1.4 on 2024-12-23 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_item_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyquest',
            name='common_items',
        ),
        migrations.RemoveField(
            model_name='dailyquest',
            name='rare_items',
        ),
        migrations.RemoveField(
            model_name='dailyquest',
            name='uncommon_items',
        ),
    ]
