# Generated by Django 5.1.4 on 2024-12-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_dailyquest_common_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyquest',
            name='drop_class',
            field=models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=20),
        ),
    ]
