# Generated by Django 5.1.4 on 2024-12-23 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_dailyquest_drop_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='backpack',
        ),
        migrations.CreateModel(
            name='BackpackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.character')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.item')),
            ],
        ),
    ]
