# Generated by Django 5.1.4 on 2024-12-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_character_backpack_backpackitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='backpack',
            field=models.ManyToManyField(blank=True, related_name='backpack_items', through='core.BackpackItem', to='core.item'),
        ),
    ]
