# Generated by Django 5.1.4 on 2024-12-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_character_backpack'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='weekly_quests_count',
            field=models.IntegerField(default=0),
        ),
    ]
