# Generated by Django 5.1.4 on 2024-12-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_customuser_weekly_quests_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='percent_weekly_completed',
            field=models.FloatField(default=0.0),
        ),
    ]
