# Generated by Django 5.1.4 on 2024-12-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_customuser_percent_weekly_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='completed_quests',
            field=models.IntegerField(default=0),
        ),
    ]
