# Generated by Django 5.1.4 on 2024-12-26 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_customuser_completed_quests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='level',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='rank',
        ),
        migrations.AddField(
            model_name='character',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='character',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.rank'),
        ),
    ]
