# Generated by Django 5.1.4 on 2024-12-26 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_customuser_level_remove_customuser_rank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='character', to='core.rank'),
        ),
    ]
