# Generated by Django 5.1.4 on 2024-12-26 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_character_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backpackitem',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.character'),
        ),
        migrations.AlterField(
            model_name='backpackitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.item'),
        ),
        migrations.AlterField(
            model_name='character',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character', to='core.rank'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character', to='core.character'),
        ),
    ]
