# Generated by Django 5.1.4 on 2024-12-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_backpackitem_character_alter_backpackitem_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='exp',
            field=models.IntegerField(default=0),
        ),
    ]
