# Generated by Django 5.1.4 on 2024-12-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_character_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='target_num_quests_inc',
            field=models.IntegerField(default=0),
        ),
    ]
