# Generated by Django 5.1.4 on 2025-01-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_customuser_target_num_quests_inc'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='marketable',
            field=models.BooleanField(default=False),
        ),
    ]
