# Generated by Django 5.1.4 on 2025-01-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_item_marketable'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='market_drop_rate',
            field=models.FloatField(default=50.0),
        ),
    ]
