# Generated by Django 5.1.4 on 2025-01-05 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_item_market_drop_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='gold',
            field=models.IntegerField(default=0),
        ),
    ]
