# Generated by Django 5.1.4 on 2025-01-05 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_character_gold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyquest',
            name='quest_description',
            field=models.TextField(),
        ),
    ]
