# Generated by Django 5.1.4 on 2025-01-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_dailyquest_quest_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gotten_quests',
            field=models.BooleanField(default=False),
        ),
    ]
