# Generated by Django 5.1.4 on 2025-01-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_customuser_gotten_quests'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='quests',
            field=models.ManyToManyField(related_name='characters', to='core.dailyquest'),
        ),
    ]
