# Generated by Django 5.1.4 on 2025-01-09 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_character_quests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='damage',
        ),
        migrations.RemoveField(
            model_name='item',
            name='healing',
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('ingredient', 'Ingredient'), ('object', 'Object')], default='ingredient', max_length=20),
        ),
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defense', models.IntegerField()),
                ('resistance', models.IntegerField(blank=True, null=True)),
                ('crafting_ingredients', models.ManyToManyField(related_name='used_for_armor', to='core.item')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='armor', to='core.item')),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage', models.IntegerField()),
                ('attack_speed', models.FloatField(default=1.0)),
                ('critical_rate', models.FloatField(default=0.0)),
                ('crafting_ingredients', models.ManyToManyField(related_name='used_for_weapon', to='core.item')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weapon', to='core.item')),
            ],
        ),
    ]
