# Generated by Django 5.1.4 on 2025-01-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_item_damage_remove_item_healing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armor',
            name='item',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='item',
        ),
        migrations.AddField(
            model_name='armor',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='armor',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='weapon',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weapon',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
