# Generated by Django 5.1.4 on 2025-01-11 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_remove_armor_item_remove_weapon_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='armor',
            name='durability',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='weapon',
            name='durability',
            field=models.IntegerField(default=10),
        ),
    ]
