# Generated by Django 5.1.4 on 2025-01-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_armor_durability_weapon_durability'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='forgeIngredient',
            field=models.BooleanField(default=False),
        ),
    ]
