# Generated by Django 5.1.4 on 2025-01-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_item_forgeingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='armor',
            field=models.ManyToManyField(blank=True, related_name='characters', to='core.armor'),
        ),
        migrations.AddField(
            model_name='character',
            name='weapons',
            field=models.ManyToManyField(blank=True, related_name='characters', to='core.weapon'),
        ),
    ]
