# Generated by Django 5.1.4 on 2025-01-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_character_armor_character_weapons'),
    ]

    operations = [
        migrations.AddField(
            model_name='armor',
            name='forgeable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weapon',
            name='forgeable',
            field=models.BooleanField(default=False),
        ),
    ]
