# Generated by Django 5.1.4 on 2025-01-13 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_armor_forgeable_weapon_forgeable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armor',
            name='crafting_ingredients',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='crafting_ingredients',
        ),
    ]
