# Generated by Django 5.1.4 on 2025-01-13 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_remove_armor_crafting_ingredients_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='equipablesIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('armor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.armor')),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.character')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.item')),
                ('weapon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.weapon')),
            ],
        ),
        migrations.AddField(
            model_name='armor',
            name='crafting_ingredients',
            field=models.ManyToManyField(blank=True, related_name='used_for_armor', through='core.equipablesIngredients', to='core.item'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='crafting_ingredients',
            field=models.ManyToManyField(blank=True, related_name='used_for_weapon', through='core.equipablesIngredients', to='core.item'),
        ),
    ]
