# Generated by Django 5.1.4 on 2025-01-13 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_equipablesingredients_armor_crafting_ingredients_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipablesingredients',
            name='character',
        ),
    ]
