# Generated by Django 5.1.4 on 2025-01-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_armor_repair_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='armor',
            old_name='durability',
            new_name='max_durability',
        ),
        migrations.RenameField(
            model_name='weapon',
            old_name='durability',
            new_name='max_durability',
        ),
        migrations.AddField(
            model_name='armor',
            name='current_durability',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='weapon',
            name='current_durability',
            field=models.IntegerField(default=5),
        ),
    ]
