# Generated by Django 5.1.4 on 2025-01-15 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_rename_durability_armor_max_durability_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='armor',
        ),
        migrations.RemoveField(
            model_name='character',
            name='weapons',
        ),
        migrations.CreateModel(
            name='ArmorItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_durability', models.IntegerField(default=1)),
                ('armor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.armor')),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.character')),
            ],
        ),
        migrations.CreateModel(
            name='WeaponItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_durability', models.IntegerField(default=1)),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.character')),
                ('weapon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.weapon')),
            ],
        ),
    ]
