# Generated by Django 5.1.4 on 2025-01-15 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_remove_character_armor_remove_character_weapons_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArmorItem',
            new_name='ArmorBag',
        ),
        migrations.RenameModel(
            old_name='WeaponItem',
            new_name='WeaponBag',
        ),
    ]
