# Generated by Django 5.1.4 on 2025-01-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_rename_armoritem_armorbag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='armor',
            field=models.ManyToManyField(blank=True, related_name='armor_bag', through='core.ArmorBag', to='core.armor'),
        ),
        migrations.AddField(
            model_name='character',
            name='weapons',
            field=models.ManyToManyField(blank=True, related_name='weapon_bag', through='core.WeaponBag', to='core.weapon'),
        ),
    ]
