# Generated by Django 5.1.4 on 2025-01-15 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_character_armor_character_weapons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armor',
            name='current_durability',
        ),
    ]
