# Generated by Django 5.1.4 on 2025-01-15 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_remove_armor_current_durability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapon',
            name='current_durability',
        ),
    ]
