# Generated by Django 5.1.4 on 2025-01-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_remove_weapon_current_durability'),
    ]

    operations = [
        migrations.AddField(
            model_name='armorbag',
            name='current_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='weaponbag',
            name='current_level',
            field=models.IntegerField(default=1),
        ),
    ]
