# Generated by Django 5.1.4 on 2025-01-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_armorbag_current_level_weaponbag_current_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='armorbag',
            name='upgraded_defense',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='weaponbag',
            name='upgraded_damage',
            field=models.IntegerField(default=1),
        ),
    ]
