# Generated by Django 5.1.4 on 2025-01-16 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_armorbag_upgraded_defense_weaponbag_upgraded_damage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armorbag',
            name='upgraded_defense',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weaponbag',
            name='upgraded_damage',
            field=models.IntegerField(default=0),
        ),
    ]
