# Generated by Django 5.1.4 on 2025-01-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_armorbag_upgraded_defense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='health',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='motivation',
            field=models.IntegerField(default=4),
        ),
    ]
