# Generated by Django 5.1.4 on 2025-01-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_character_health_character_motivation'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='current_health',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='current_motivation',
            field=models.IntegerField(default=2),
        ),
    ]
