# Generated by Django 5.1.4 on 2025-01-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_character_current_health_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weaponbag',
            name='weapon_efficiency',
            field=models.IntegerField(default=0),
        ),
    ]
