# Generated by Django 5.1.4 on 2025-01-22 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_weaponbag_weapon_efficiency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='skills',
        ),
        migrations.CreateModel(
            name='skillSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.character')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.skill')),
            ],
        ),
    ]
