# Generated by Django 5.1.4 on 2025-01-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_remove_character_skills_skillset'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='skill_set', through='core.skillSet', to='core.skill'),
        ),
        migrations.AddField(
            model_name='skillset',
            name='damage_modifier',
            field=models.IntegerField(default=0),
        ),
    ]
