# Generated by Django 5.1.4 on 2025-01-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_character_skills_skillset_damage_modifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(choices=[('general', 'General'), ('combat', 'Combat'), ('magic', 'Magic'), ('utility', 'Utility'), ('motivational', 'Motivational'), ('unique', 'Unique')], default='general', max_length=20),
        ),
    ]
