# Generated by Django 5.1.4 on 2025-01-28 13:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_skill_skill_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='max_damage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='max_healing',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skillset',
            name='efficiency',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
