# Generated by Django 5.1.4 on 2025-01-28 19:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_skill_max_damage_skill_max_healing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillset',
            name='efficiency',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
