# Generated by Django 5.1.4 on 2025-01-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_alter_skillset_efficiency'),
    ]

    operations = [
        migrations.AddField(
            model_name='armorbag',
            name='armor_efficiency',
            field=models.IntegerField(default=0),
        ),
    ]
