# Generated by Django 5.1.4 on 2025-01-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_armorbag_armor_efficiency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weaponbag',
            name='weapon_efficiency',
            field=models.FloatField(default=0.0),
        ),
    ]
