# Generated by Django 5.1.4 on 2025-01-29 13:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_alter_weaponbag_weapon_efficiency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weaponbag',
            name='weapon_efficiency',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
