# Generated by Django 5.1.4 on 2025-01-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_alter_weaponbag_weapon_efficiency'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillset',
            name='healing_modifier',
            field=models.IntegerField(default=0),
        ),
    ]
