# Generated by Django 5.1.4 on 2025-01-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_magic_magictome'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='magic',
            field=models.ManyToManyField(blank=True, related_name='magic_tome', through='core.magicTome', to='core.magic'),
        ),
    ]
