# Generated by Django 5.1.4 on 2025-01-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_character_magic'),
    ]

    operations = [
        migrations.AddField(
            model_name='magic',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
