# Generated by Django 5.1.4 on 2025-01-30 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_magic_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='magictome',
            old_name='weapon_efficiency',
            new_name='spell_efficiency',
        ),
    ]
