# Generated by Django 5.1.4 on 2025-02-04 12:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_rename_weapon_efficiency_magictome_spell_efficiency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='motivation',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
