# Generated by Django 5.1.4 on 2025-02-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_alter_character_motivation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipablesingredients',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
