# Generated by Django 5.1.4 on 2025-02-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_alter_equipablesingredients_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backpackitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
