# Generated by Django 5.1.4 on 2025-02-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_alter_backpackitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backpackitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='equipablesingredients',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
