# Generated by Django 5.1.4 on 2025-03-10 18:36

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_alter_backpackitem_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default='default_avatar.png', upload_to=core.models.user_directory_path),
        ),
    ]
