# Generated by Django 5.1.4 on 2025-03-21 11:56

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_customuser_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPCS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('party', models.CharField(blank=True, max_length=50, null=True)),
                ('is_traveller', models.BooleanField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('alignment', models.CharField(blank=True, choices=[('LG', 'Lawful Good'), ('CN', 'Chaotic Neutral'), ('CE', 'Chaotic Evil')], max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('is_alive', models.BooleanField(default=True)),
                ('level', models.IntegerField(blank=True, default=1, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.NPC_directory_path)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('THEY', 'They')], max_length=10, null=True)),
                ('race', models.CharField(blank=True, choices=[('HUMAN', 'Human'), ('', 'Yes')], max_length=10, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default='default_avatar.png', upload_to=core.models.user_directory_path, validators=[core.models.validate_file_type, core.models.validate_file_size]),
        ),
    ]
