# Generated by Django 5.1.4 on 2025-03-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_npcs_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='questBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questName', models.CharField(max_length=100)),
                ('questType', models.CharField(blank=True, choices=[('Adventure', 'Adventure'), ('Kill', 'Kill'), ('Capture', 'Capture')], max_length=40, null=True)),
                ('Difficulty', models.CharField(blank=True, choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=40, null=True)),
                ('goldValue', models.FloatField(blank=True, null=True)),
                ('reputation', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
