# Generated by Django 5.1.4 on 2025-03-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_questboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='questboard',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
