# Generated by Django 5.1.4 on 2025-03-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_questboard_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='questboard',
            name='can_refresh',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questboard',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='questboard',
            name='questType',
            field=models.CharField(blank=True, choices=[('Adventure', 'Adventure'), ('Kill', 'Kill'), ('Capture', 'Capture'), ('Other', 'Other')], max_length=40, null=True),
        ),
    ]
