# Generated by Django 5.1.4 on 2025-03-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_questboard_can_refresh_questboard_is_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questboard',
            name='complete_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
