# Generated by Django 5.1.4 on 2025-03-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_questboard_complete_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questboard',
            name='complete_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
