# Generated by Django 5.1.4 on 2025-03-25 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_alter_questboard_complete_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questboard',
            name='complete_time',
        ),
        migrations.RemoveField(
            model_name='questboard',
            name='is_completed',
        ),
        migrations.CreateModel(
            name='characterGuildQuests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('duration_hours', models.FloatField()),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.character')),
                ('quest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.questboard')),
            ],
        ),
    ]
