# Generated by Django 5.1.4 on 2025-03-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_remove_questboard_complete_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterguildquests',
            name='duration_hours',
        ),
        migrations.AddField(
            model_name='questboard',
            name='duration_hours',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
