# Generated by Django 5.1.4 on 2025-03-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_remove_characterguildquests_duration_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterguildquests',
            name='duration_hours',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
