# Generated by Django 5.1.4 on 2025-03-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_characterguildquests_duration_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='npcs',
            name='prompt',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
