# Generated by Django 5.1.4 on 2025-04-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_bulletinboard'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bulletinBoard',
            new_name='bulletinBoardExtra',
        ),
        migrations.AddField(
            model_name='questboard',
            name='bulletinBoardEntry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
