# Generated by Django 5.1.4 on 2025-04-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_rename_bulletinboard_bulletinboardextra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questboard',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
