# Generated by Django 5.1.4 on 2025-04-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_questboard_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gotten_guild_quests',
            field=models.BooleanField(default=False),
        ),
    ]
