# Generated by Django 5.1.4 on 2025-04-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_character_guildquests'),
    ]

    operations = [
        migrations.CreateModel(
            name='dailyGuildQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest_name', models.CharField(max_length=50)),
                ('quest_description', models.TextField()),
                ('drop_class', models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='character',
            name='guildQuests',
            field=models.ManyToManyField(related_name='character', to='core.dailyguildquest'),
        ),
    ]
