# Generated by Django 5.1.4 on 2025-04-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_dailyguildquest_alter_character_guildquests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyguildquest',
            name='quest_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
