# Generated by Django 5.1.4 on 2025-04-10 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_alter_dailyguildquest_quest_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='guildQuests',
        ),
        migrations.DeleteModel(
            name='dailyGuildQuest',
        ),
    ]
