# Generated by Django 5.1.4 on 2025-04-10 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_remove_character_guildquests_delete_dailyguildquest'),
    ]

    operations = [
        migrations.CreateModel(
            name='characterGottenGQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.character')),
                ('quest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.questboard')),
            ],
        ),
    ]
