# Generated by Django 5.1.4 on 2025-04-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_charactergottengq'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='guildQuests',
            field=models.ManyToManyField(related_name='character', to='core.questboard'),
        ),
    ]
