# Generated by Django 5.1.4 on 2025-04-10 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_character_guildquests'),
    ]

    operations = [
        migrations.DeleteModel(
            name='characterGottenGQ',
        ),
    ]
