# Generated by Django 5.1.4 on 2025-04-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_delete_charactergottengq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questboard',
            name='bulletinBoardEntry',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
