# Generated by Django 5.1.4 on 2025-04-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_alter_questboard_bulletinboardentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='questboard',
            name='drop_class',
            field=models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=20),
        ),
    ]
