# Generated by Django 5.1.4 on 2025-04-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_questboard_drop_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='towns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('population', models.PositiveIntegerField(default=0)),
                ('defense_level', models.PositiveIntegerField(default=0)),
                ('monster_threat_level', models.PositiveIntegerField(default=0)),
                ('reputation', models.JSONField(blank=True, default=dict)),
                ('chronicle', models.JSONField(blank=True, default=list)),
                ('travel_time', models.PositiveIntegerField(default=0)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
            ],
        ),
    ]
