# Generated by Django 5.1.4 on 2025-04-24 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_towns'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPCDialogueRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(max_length=200)),
                ('response', models.TextField()),
                ('condition_flag', models.CharField(blank=True, max_length=100, null=True)),
                ('npc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogue_rules', to='core.npcs')),
            ],
        ),
    ]
