# Generated by Django 5.1.4 on 2025-04-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_npcdialoguerule'),
    ]

    operations = [
        migrations.AddField(
            model_name='npcs',
            name='attitude',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
