# Generated by Django 5.1.4 on 2025-05-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_npcs_attitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='bugs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('in progress', 'In progress'), ('Investigating', 'investigating'), ('Fix Scheduled', 'fix scheduled'), ('Completed', 'completed')], default='Investigating', max_length=30)),
            ],
        ),
    ]
