# Generated by Django 5.1.4 on 2025-05-06 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_bugs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bugs',
            new_name='BugsModel',
        ),
    ]
