# Generated by Django 5.1.4 on 2025-05-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_rename_bugs_bugsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugsmodel',
            name='workaround',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
