# Generated by Django 5.1.4 on 2025-05-07 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_usertasks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userTasks',
            new_name='userDefinedTasks',
        ),
    ]
