# Generated by Django 5.1.4 on 2025-05-09 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_rename_usertasks_userdefinedtasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='taskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest_name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=400)),
                ('experience_points', models.IntegerField()),
                ('drop_class', models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=20)),
                ('frequency', models.CharField(choices=[('Everyday', 'Everyday'), ('Random', 'Random')], max_length=20)),
                ('source', models.CharField(choices=[('system', 'System'), ('user', 'User')], max_length=10)),
                ('creator', models.ForeignKey(blank=True, help_text='Only set for tasks created by users', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
