# Generated by Django 5.1.4 on 2025-05-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_taskmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='quests',
            field=models.ManyToManyField(related_name='characters', to='core.taskmodel'),
        ),
    ]
