# Generated by Django 5.1.4 on 2025-05-09 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_alter_character_quests'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dailyQuest',
        ),
        migrations.DeleteModel(
            name='userDefinedTasks',
        ),
    ]
