# Generated by Django 5.1.4 on 2025-05-20 15:19

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_delete_dailyquest_delete_userdefinedtasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='enemies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enemy_name', models.CharField(max_length=50)),
                ('base_damage', models.IntegerField()),
                ('base_armor', models.IntegerField()),
                ('health', models.IntegerField()),
                ('is_boss', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.NPC_directory_path)),
                ('gold_drop', models.IntegerField()),
                ('mana', models.IntegerField(blank=True, null=True)),
                ('level', models.IntegerField(default=1)),
                ('drop_class', models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=20)),
                ('armor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.armor')),
                ('magic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.magic')),
                ('weapon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.weapon')),
            ],
        ),
    ]
