# Generated by Django 5.1.4 on 2025-05-20 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_enemies'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='enemies',
            new_name='enemie',
        ),
    ]
