# Generated by Django 5.1.4 on 2025-05-20 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_rename_enemies_enemie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='enemie',
            new_name='enemies',
        ),
    ]
