# Generated by Django 5.1.4 on 2025-05-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_rename_enemie_enemies'),
    ]

    operations = [
        migrations.AddField(
            model_name='armor',
            name='type',
            field=models.CharField(blank=True, choices=[('boots', 'Boots'), ('helmet', 'Helmet'), ('chest', 'Chest'), ('legs', 'Legs')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='armorbag',
            name='dexterity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='dexterity',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='enemies',
            name='dexterity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='magictome',
            name='dexterity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='dexterity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
