# Generated by Django 5.1.4 on 2025-05-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0112_armor_type_armorbag_dexterity_character_dexterity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='npcs',
            name='dexterity',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='armor',
            name='type',
            field=models.CharField(blank=True, choices=[('boots', 'Boots'), ('helmet', 'Helmet'), ('chest', 'Chest'), ('legs', 'Legs'), ('arms', 'Arms')], max_length=20, null=True),
        ),
    ]
