# Generated by Django 5.1.4 on 2025-05-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_npcs_dexterity_alter_armor_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='dexterity',
        ),
        migrations.AddField(
            model_name='skillset',
            name='dexterity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
