# Generated by Django 5.1.4 on 2025-05-23 14:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_remove_skill_dexterity_skillset_dexterity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rankdetail',
            old_name='special_attack',
            new_name='attack',
        ),
        migrations.RenameField(
            model_name='rankdetail',
            old_name='special_attack_damage',
            new_name='damage',
        ),
        migrations.RemoveField(
            model_name='armorbag',
            name='armor_efficiency',
        ),
        migrations.RemoveField(
            model_name='armorbag',
            name='upgraded_defense',
        ),
        migrations.RemoveField(
            model_name='magictome',
            name='spell_efficiency',
        ),
        migrations.RemoveField(
            model_name='magictome',
            name='upgraded_damage',
        ),
        migrations.RemoveField(
            model_name='magictome',
            name='upgraded_healing',
        ),
        migrations.RemoveField(
            model_name='weaponbag',
            name='upgraded_damage',
        ),
        migrations.RemoveField(
            model_name='weaponbag',
            name='weapon_efficiency',
        ),
        migrations.AddField(
            model_name='armorbag',
            name='defense_modifier',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='armorbag',
            name='efficiency',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='magictome',
            name='damage_modifier',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='magictome',
            name='efficiency',
            field=models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='magictome',
            name='healing_modifier',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='weaponbag',
            name='damage_modifier',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='weaponbag',
            name='efficiency',
            field=models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='skillset',
            name='damage_modifier',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='skillset',
            name='efficiency',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='skillset',
            name='healing_modifier',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
