# Generated by Django 5.1.4 on 2025-05-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0115_rename_special_attack_rankdetail_attack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='armorbag',
            name='current_equip',
            field=models.BooleanField(default=False),
        ),
    ]
