# Generated by Django 5.1.4 on 2025-05-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0116_armorbag_current_equip'),
    ]

    operations = [
        migrations.AddField(
            model_name='armorbag',
            name='standby_armor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weaponbag',
            name='current_equip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weaponbag',
            name='standby_weapon',
            field=models.BooleanField(default=False),
        ),
    ]
