# Generated by Django 5.1.4 on 2025-06-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_armorbag_standby_armor_weaponbag_current_equip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryScene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_id', models.CharField(max_length=100, unique=True)),
                ('content_json', models.JSONField()),
            ],
        ),
    ]
