# Generated by Django 5.1.4 on 2025-06-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0118_storyscene'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='current_story_quest',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
