# Generated by Django 5.1.4 on 2025-06-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0119_character_current_story_quest'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='dungeon_quest_available',
            field=models.BooleanField(default=False),
        ),
    ]
