# Generated by Django 5.1.4 on 2025-06-25 03:33

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0120_character_dungeon_quest_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='url',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.weapon_directory_path),
        ),
    ]
