# Generated by Django 5.1.4 on 2025-06-25 03:35

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0121_weapon_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='armor',
            name='url',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.armor_directory_path),
        ),
    ]
