# Generated by Django 5.1.4 on 2025-07-24 11:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0122_armor_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='completed_tutorial',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='magictome',
            name='efficiency',
            field=models.FloatField(blank=True, default=1.0, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='weaponbag',
            name='efficiency',
            field=models.FloatField(blank=True, default=1.0, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
