# Generated by Django 5.1.4 on 2025-07-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0123_customuser_completed_tutorial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='fuelMyFire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=2000, unique=True)),
            ],
        ),
    ]
