# Generated by Django 5.1.4 on 2025-07-31 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0127_usertestament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='dexterity',
            field=models.FloatField(blank=True, default=0.5, null=True),
        ),
    ]
