# Generated by Django 5.1.4 on 2025-07-31 19:48

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0128_alter_character_dexterity'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='story_avatar',
            field=models.ImageField(default='default_avatar.png', upload_to=core.models.character_avatar_directory_path, validators=[core.models.validate_file_type, core.models.validate_file_size]),
        ),
    ]
