# Generated by Django 5.1.4 on 2025-08-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0129_character_story_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='donated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscription',
            field=models.BooleanField(default=False),
        ),
    ]
