# Generated by Django 5.1.4 on 2025-08-14 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0130_customuser_donated_customuser_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillset',
            name='efficiency',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
